// Code generated by go generate; DO NOT EDIT.
package main

import "strconv"

var pattern = [15]string{ "FizzBuzz", "", "", "Fizz", "", "Buzz", "Fizz", "", "", "Fizz", "Buzz", "", "Fizz", "", "" }
var max = 15

func FizzBuzz(n int) string {
	s := pattern[n % max]
	if s == "" {
		return strconv.Itoa(n)
	}
	return s
}
